version: 2

terraform: &terraform
  docker:
    - image: qualimente/terraform-infra-dev:0.11.10
  working_directory: /module

jobs:
  build:
    <<: *terraform
    steps:
      - checkout
      - run:
          name: add github.com to ~/.ssh/known_hosts
          command: mkdir -p ~/.ssh && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - run:
          name: make infra
          working_directory: /module/aws/multi_tier_app/
          command: make all
      - store_artifacts:
          path: /module/aws/multi_tier_app/.kitchen/
      - run:
          name: destroy minimal test infra
          working_directory: /module/aws/multi_tier_app/
          command: make destroy
